// UI REDUCER
const SET_THEME = "SET_THEME";
const SET_LANG = "SET_LANG";

const LOADING = 'LOADING'

const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
const LOGOUT = 'LOGOUT';

const FETCH_STUDENTS = 'FETCH_STUDENTS';
const SELECT_STUDENT = 'SELECT_STUDENT';


export {
    SET_THEME,
    SET_LANG,
    LOGIN_SUCCESS,
    LOGOUT_SUCCESS,
    LOGOUT,
    LOADING,
    FETCH_STUDENTS,
    SELECT_STUDENT
}